### ISSUE TITLE
SQLite Locking Protocol error on CephFS

### ISSUE THREAD

**Issue by JJGadgets** [zgoat/zdb#3]
Hey, I'm using GoatCounter which uses zdb, and my backing database is SQLite. The SQLite data is stored on CephFS, and all this is run on my home Kubernetes cluster.

It seems like zdb's SQLite mode doesn't like CephFS very well. CephFS is a networked filesystem, but AFAIK it has much better lock handling than NFS, and so far I haven't had any other SQLite apps on my home cluster give lock errors besides GoatCounter.

I've attached a screenshot of some of the logs from GoatCounter that show the "Locking Protocol" error which seems to originate from SQLite itself. 

Also, I'm using my own distroless container image of GoatCounter which simply downloads the binary from the releases (so I'm not `go build`ing anything myself), here's the Dockerfile: (https://github.com/JJGadgets/containers/blob/7b2c4f33d7e6ef74cf5f7e0fe9f33d513388c83f/apps/goatcounter/Dockerfile#L26)

![image](https://github.com/user-attachments/assets/bbbd32bd-007b-4d29-903b-1297e196af34)

**Comment by arp242** [comment]
I don't know; it just uses SQLite. There is nothing special here really.

So use PostgreSQL or don't use a network filesystem I guess.

**Comment by JJGadgets** [comment]
Sorry, user error, bad SQLite path config in the args. Hasn't errored ever since I fixed that, even on CephFS, so I think it's good now.
